In [1]:
#data source https://covid.ourworldindata.org/data/owid-covid-data.json

import pandas as pd
import json

In [2]:
df = pd.read_json("https://covid.ourworldindata.org/data/owid-covid-data.json")

In [4]:
data = df.transpose()

In [33]:
data

,continent,location,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,data,extreme_poverty,female_smokers,male_smokers
AFG,Asia,Afghanistan,3.89283e+07,54.422,18.6,2.581,1.337,1803.99,597.029,9.59,37.746,0.5,64.83,0.511,"[{'date': '2020-02-24', 'total_cases': 1.0, 'n...",NaN,NaN,NaN
OWID_AFR,NaN,Africa,1.3406e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"[{'date': '2020-02-13', 'new_cases': 0.0, 'new...",NaN,NaN,NaN
ALB,Europe,Albania,2.8778e+06,104.871,38,13.188,8.643,11803.4,304.195,10.08,NaN,2.89,78.57,0.795,"[{'date': '2020-02-25', 'new_tests': 8.0, 'tot...",1.1,7.1,51.2
DZA,Africa,Algeria,4.3851e+07,17.348,29.1,6.211,3.857,13913.8,278.364,6.73,83.741,1.9,76.88,0.748,"[{'date': '2020-02-25', 'total_cases': 1.0, 'n...",0.5,0.7,30.4
AND,Europe,Andorra,77265,163.755,NaN,NaN,NaN,NaN,109.135,7.97,NaN,NaN,83.73,0.868,"[{'date': '2020-03-02', 'total_cases': 1.0, 'n...",NaN,29,37.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VNM,Asia,Vietnam,9.73386e+07,308.127,32.6,7.15,4.718,6171.88,245.465,6,85.847,2.6,75.4,0.704,"[{'date': '2020-01-23', 'total_cases': 2.0, 'n...",2,1,45.9
OWID_WRL,NaN,World,7.7948e+09,58.045,30.9,8.696,5.355,15469.2,233.07,8.51,60.13,2.705,72.58,0.737,"[{'date': '2020-01-22', 'total_cases': 557.0, ...",10,6.434,34.635
YEM,Asia,Yemen,2.9826e+07,53.508,20.3,2.922,1.583,1479.15,495.003,5.35,49.542,0.7,66.12,0.47,"[{'date': '2020-04-10', 'total_cases': 1.0, 'n...",18.8,7.6,29.2
ZMB,Africa,Zambia,1.8384e+07,22.995,17.7,2.48,1.542,3689.25,234.499,3.94,13.938,2,63.89,0.584,"[{'date': '2020-03-18', 'total_cases': 2.0, 'n...",57.5,3.1,24.7
ZWE,Africa,Zimbabwe,1.48629e+07,42.729,19.6,2.822,1.882,1899.78,307.846,1.82,36.791,1.7,61.49,0.571,"[{'date': '2020-03-20', 'total_cases': 1.0, 'n...",21.4,1.6,30.7

In [44]:
case = pd.DataFrame()
cont = pd.DataFrame()

for row in range(len(data)):
    loc = data.iloc[row,1]
    temp_df = pd.DataFrame(data.iloc[row,14])
    temp_df["location"] = loc
    #split continent and country
    if(pd.isna(data.iloc[row,0])):
        cont = cont.append(temp_df, ignore_index=True)    
    else:
        temp_df["continent"] = data.iloc[row,0]
        case = case.append(temp_df, ignore_index=True)

In [47]:
case.to_csv("country_data.csv")
cont.to_csv("continent_data.csv")
data.drop("data",axis=1).to_csv("sum_data.csv")

In [46]:
data.drop("data",axis=1)

,continent,location,population,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,cardiovasc_death_rate,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,extreme_poverty,female_smokers,male_smokers
AFG,Asia,Afghanistan,3.89283e+07,54.422,18.6,2.581,1.337,1803.99,597.029,9.59,37.746,0.5,64.83,0.511,NaN,NaN,NaN
OWID_AFR,NaN,Africa,1.3406e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ALB,Europe,Albania,2.8778e+06,104.871,38,13.188,8.643,11803.4,304.195,10.08,NaN,2.89,78.57,0.795,1.1,7.1,51.2
DZA,Africa,Algeria,4.3851e+07,17.348,29.1,6.211,3.857,13913.8,278.364,6.73,83.741,1.9,76.88,0.748,0.5,0.7,30.4
AND,Europe,Andorra,77265,163.755,NaN,NaN,NaN,NaN,109.135,7.97,NaN,NaN,83.73,0.868,NaN,29,37.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
VNM,Asia,Vietnam,9.73386e+07,308.127,32.6,7.15,4.718,6171.88,245.465,6,85.847,2.6,75.4,0.704,2,1,45.9
OWID_WRL,NaN,World,7.7948e+09,58.045,30.9,8.696,5.355,15469.2,233.07,8.51,60.13,2.705,72.58,0.737,10,6.434,34.635
YEM,Asia,Yemen,2.9826e+07,53.508,20.3,2.922,1.583,1479.15,495.003,5.35,49.542,0.7,66.12,0.47,18.8,7.6,29.2
ZMB,Africa,Zambia,1.8384e+07,22.995,17.7,2.48,1.542,3689.25,234.499,3.94,13.938,2,63.89,0.584,57.5,3.1,24.7
ZWE,Africa,Zimbabwe,1.48629e+07,42.729,19.6,2.822,1.882,1899.78,307.846,1.82,36.791,1.7,61.49,0.571,21.4,1.6,30.7